### ISSUE TITLE
Wrong row count in executions UI landing page

### ISSUE THREAD

**Issue by bimal10** [orkes-io/orkes-conductor-community#4]
**Describe the bug**
In Ui even though there are many execution requests it does not show  correct row and pagination count 

**Steps To Reproduce**
1. Make sure you have many executions in prior preferably more than 15

2. Go to Executions tab, keep default view count of executions as 15, the page nav icons are disabled and number of executions count is wrongly displayed
![Screenshot 2022-09-16 at 1 09 21 PM](https://user-images.githubusercontent.com/25317852/190584303-fcb3ef13-1152-4cca-949c-0a6448e744ae.png)

3. Click on drop down to increase row count and you will be able to more extra records 
![Screenshot 2022-09-16 at 1 13 49 PM](https://user-images.githubusercontent.com/25317852/190584630-b8926c07-904f-42db-ad2c-cba21bf729f6.png)

**Expected behavior**
Rows count should be correct and also the nav icons allow to navigate.  

**Additional context**
These workflows were spawn from backend using locahost:1234 endpoints not via UI workbench. Thanks

**Comment by pablocubico** [comment]
Thanks @bimal10, we'll look into this
